--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/usy4/JoinStreak
build-by-default: true
branches:
- main
projects:
  JoinStreak:
    path: ""
    icon: "JoinStreak.png"
    libs:
      - src: "CortexPE/Commando/Commando"
        branch: "PM4"
        version: ^3.0.0
...
